### ISSUE TITLE
MyAnimeList scores still visible on Home page and Advanced Search

### ISSUE THREAD

**Issue by DUser6** [Dem1se/hide-ratings-extension-firefox#7]
You can still see user ratings on MAL's home page in the "Top Airing", "Top Upcoming", and "Most Popular" boxes on the right. Also, when using Advanced Search, user ratings are still visible on the results page.
![Screenshot 2022-09-01 at 09-49-18 MyAnimeList net - Anime and Manga Database and Community](https://user-images.githubusercontent.com/98536563/187930967-2ce8d709-25ad-4234-8183-68252d7a40cb.png)

![Screenshot 2022-09-01 at 09-50-13 Search Anime - MyAnimeList net](https://user-images.githubusercontent.com/98536563/187930951-b5d5e739-da30-45a9-bff2-ba3da8afa00c.png)

**Comment by nithssh** [comment]
This extension has been upstreamed, please report any issues in the [upstream repo](https://github.com/ganigeorgiev/hide-ratings-extension)
